import z from "zod";
import "../config/zod-extend.js";

export const sendOtpSchema = z
    .object({
        email: z.email().trim().openapi({ example: "jane@example.com" }),
    })
    .openapi("SendOtpInput");

export type SendOtpInput = z.infer<typeof sendOtpSchema>;

export const verifyEmailSchema = z
    .object({
        email: z.email().trim().openapi({ example: "jane@example.com" }),
        otp: z
            .string()
            .regex(/^\d{6}$/, "OTP must be 6 digits")
            .openapi({ example: "123456" }),
    })
    .openapi("VerifyEmailInput");

export type VerifyEmailInput = z.infer<typeof verifyEmailSchema>;

export const registerUserSchema = z
    .object({
        name: z
            .string()
            .trim()
            .min(3, "Name must be at least 3 characters")
            .openapi({ example: "Jane Doe" }),
        email: z.email().trim().openapi({ example: "jane@example.com" }),
        password: z
            .string()
            .min(5, "Password must be at least 5 characters")
            .openapi({ example: "strongpw" }),
    })
    .openapi("RegisterUserInput");
export type RegisterUserInput = z.infer<typeof registerUserSchema>;

export const loginUserSchema = z
    .object({
        email: z.email().trim().openapi({ example: "jane@example.com" }),
        password: z
            .string()
            .nonempty("Password is required")
            .openapi({ example: "strongpassword123" }),
    })
    .openapi("LoginUserInput");

export type LoginUserInput = z.infer<typeof loginUserSchema>;

export const loginResponseSchema = z
    .object({
        accessToken: z.string().openapi({
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        }),
        refreshToken: z.string().openapi({
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        }),
    })
    .openapi("LoginUserResponse");

export const refreshTokenResponseSchema = z.string().openapi({
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
});

export const verify2FASchema = z
    .object({
        code: z
            .string()
            .trim()
            .regex(/^\d{6}$/, "2FA code must be exactly 6 digits")
            .openapi({
                example: "123456",
                description: "6-digit code generated by the user's authenticator app",
            }),
    })
    .openapi("Verify2FAInput");

export type Verify2FAInput = z.infer<typeof verify2FASchema>;
